disable_existing_loggers: false
formatters:
  complete_time:
    datefmt: '%Y%m%d %H:%M:%S'
    format: '[ %(levelname)-8s ] [ %(name)-13s ] [ %(asctime)s ] %(message)s'
  console_format:
    format: '[ %(levelname)-8s ] [ %(name)-13s ] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: console_format
    level: WARNING
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    filename: .\log\startup.txt
    formatter: complete_time
    level: DEBUG
loggers:
  MAIN:
    handlers:
    - console
    - file
    level: DEBUG
    propagate: false
root:
  handlers:
  - file
  - console
  level: DEBUG
  propagate: false
version: 1
